spring.application.name=conviteplus+

spring.resources.static-locations=classpath:/static/

spring.datasource.url=jdbc:postgresql://localhost:5432/convitePlus
spring.datasource.username=postgres
spring.datasource.password=32321132
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jackson.default-property-inclusion=non-null
spring.jackson.serialization.fail-on-empty-beans=false

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
